name: Deploy to Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}           # e.g., 18.214.60.96
          username: ${{ secrets.SSH_USER }}       # e.g., ubuntu
          key: ${{ secrets.SSH_KEY }}             # Private key stored in GitHub Secrets
          script: |
            cd /home/ubuntu/MarmaAdmin_BE
            git pull origin main
            npm install
            pm2 restart all
